name: Tests

on:
  push:
    branches: [ trunk]
  pull_request:
    branches: [ trunk]

jobs:
  smoke-test:
    runs-on: "ubuntu-latest"
    container: ${{ matrix.distro }}
    strategy:
      matrix:
        distro: [ "fedora" ]
        include:
          - distro: alpine

    steps:
      - uses: actions/checkout@v2
      - name: Run smoke tests on ${{ matrix.distro }}
        run: . test/smoke-portable.sh
